services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    platform: linux/amd64
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      CLICKHOUSE_USER: admin
      CLICKHOUSE_PASSWORD: admin_password
    volumes:
      - clickhouse_data:/var/lib/clickhouse

  ssb_loader:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ssb_loader
    depends_on:
      - clickhouse
    entrypoint: ["/bin/bash", "-c", "/opt/load_data.sh && exit 0"]
    volumes:
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

volumes:
  clickhouse_data:
