services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    platform: linux/amd64
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      CLICKHOUSE_USER: admin
      CLICKHOUSE_PASSWORD: admin_password
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

  ssb_loader:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ssb_loader
    depends_on:
      - clickhouse
    volumes:
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    command: ["bash", "/opt/load_data.sh"]

volumes:
  clickhouse_data:
